"""
report_agent.py — SWARAMA Report Agent
Collects results from all agents in a run, generates JSON reports,
and produces a plain-text summary for email.
"""

import asyncio
import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger("swarama.report_agent")

# Reports directory — two levels up from this file's analysis/reporting location
REPORTS_DIR = Path(__file__).resolve().parents[2] / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def _determine_overall_status(agent_results: list[dict]) -> str:
    """
    Determine overall system status from all agent results.
    CRITICAL → any agent returned CRITICAL
    FAIL     → any agent returned FAIL
    WARN     → any agent returned WARN
    PASS     → everything passed
    """
    statuses = {r.get("status", "UNKNOWN") for r in agent_results}
    if "CRITICAL" in statuses:
        return "CRITICAL"
    if "FAIL" in statuses:
        return "FAIL"
    if "WARN" in statuses:
        return "WARN"
    return "PASS"


def _build_report(agent_results: list[dict], run_start_time: float) -> dict:
    """Build the full structured JSON report."""
    total_duration_ms = int((time.monotonic() - run_start_time) * 1000)

    passed = [r for r in agent_results if r.get("status") == "PASS"]
    failed = [r for r in agent_results if r.get("status") in ("FAIL", "CRITICAL", "WARN")]

    failures_detail = []
    for r in failed:
        failures_detail.append({
            "agent": r.get("agent", "unknown"),
            "status": r.get("status"),
            "timestamp": r.get("timestamp"),
            "duration_ms": r.get("duration_ms"),
            "details": r.get("details", {}),
        })

    overall_status = _determine_overall_status(agent_results)

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "overall_status": overall_status,
        "agents_total": len(agent_results),
        "agents_passed": len(passed),
        "agents_failed": len(failed),
        "duration_total_ms": total_duration_ms,
        "failures_detail": failures_detail,
        "all_results": [
            {
                "agent": r.get("agent"),
                "status": r.get("status"),
                "duration_ms": r.get("duration_ms"),
            }
            for r in agent_results
        ],
    }


def _build_plain_text_summary(report: dict) -> str:
    """Build a human-readable plain-text email body from the report."""
    ts = report["timestamp"]
    status = report["overall_status"]
    total = report["agents_total"]
    passed = report["agents_passed"]
    failed_count = report["agents_failed"]
    duration_s = report["duration_total_ms"] / 1000

    lines = [
        f"SWARAMA System Report — {ts}",
        "=" * 60,
        f"Overall Status : {status}",
        f"Agents Run     : {total}",
        f"Agents Passed  : {passed}",
        f"Agents Failed  : {failed_count}",
        f"Total Duration : {duration_s:.1f}s",
        "",
    ]

    if report["failures_detail"]:
        lines.append("FAILURES:")
        lines.append("-" * 40)
        for f in report["failures_detail"]:
            lines.append(f"  ❌ {f['agent']} — {f['status']}")
            details = f.get("details", {})

            # Include root cause if present (from root_cause_agent)
            if "root_cause" in details:
                lines.append(f"     Root cause : {details['root_cause']}")
            if "suggested_fix" in details:
                lines.append(f"     Fix        : {details['suggested_fix'][:120]}")

            # Generic failures list
            for failure_item in details.get("failures", []):
                if isinstance(failure_item, dict):
                    ep = failure_item.get("endpoint", "")
                    err = failure_item.get("error", failure_item.get("reason", ""))
                    lines.append(f"     • {ep}: {err}")
        lines.append("")

    lines.append("All agent results:")
    lines.append("-" * 40)
    for r in report["all_results"]:
        icon = "✅" if r["status"] == "PASS" else ("⚠️" if r["status"] == "WARN" else "❌")
        lines.append(f"  {icon} {r['agent']:<35} {r['status']:<10} {r['duration_ms']}ms")

    lines.append("")
    lines.append("Generated by SWARAMA agent system.")
    return "\n".join(lines)


async def run(
    agent_results: list[dict],
    run_start_time: float | None = None,
    system_state: dict | None = None,
) -> dict:
    """
    Generate a JSON report and plain-text summary for all agent results.

    Args:
        agent_results: List of result dicts from all agents in this run.
        run_start_time: monotonic start time of the full run (used for total duration).
        system_state: Optional shared orchestrator state.

    Returns:
        Standard agent result dict with report_path and plain_text_summary.
    """
    start = time.monotonic()
    agent_name = "report_agent"
    timestamp_str = datetime.now(timezone.utc).isoformat()

    if run_start_time is None:
        run_start_time = start

    logger.info("[%s] Building report from %d agent results", agent_name, len(agent_results))

    report = _build_report(agent_results, run_start_time)
    plain_text = _build_plain_text_summary(report)

    # Save JSON report
    report_filename = datetime.now(timezone.utc).strftime("%Y-%m-%d-%H") + ".json"
    report_path = REPORTS_DIR / report_filename
    try:
        with open(report_path, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2, default=str)
        logger.info("[%s] Report saved: %s", agent_name, report_path)
    except Exception as exc:
        logger.error("[%s] Failed to save report: %s", agent_name, exc)
        report_path = None

    duration_ms = int((time.monotonic() - start) * 1000)

    result = {
        "agent": agent_name,
        "status": "PASS",
        "timestamp": timestamp_str,
        "duration_ms": duration_ms,
        "details": {
            "report_path": str(report_path) if report_path else None,
            "report_filename": report_filename,
            "overall_status": report["overall_status"],
            "agents_passed": report["agents_passed"],
            "agents_failed": report["agents_failed"],
            "duration_total_ms": report["duration_total_ms"],
            "plain_text_summary": plain_text,
            "report": report,
        },
    }

    logger.info("[%s] Done — overall_status=%s report=%s",
                agent_name, report["overall_status"], report_path)
    return result


# ---------------------------------------------------------------------------
# Standalone entrypoint
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)

    import asyncio

    fake_results = [
        {"agent": "qa_agent", "status": "PASS", "timestamp": timestamp_str := datetime.now(timezone.utc).isoformat(), "duration_ms": 312, "details": {}},
        {"agent": "load_agent", "status": "FAIL", "timestamp": timestamp_str, "duration_ms": 8420, "details": {"failures": [{"endpoint": "/api/bookings", "error": "Timeout"}]}},
        {"agent": "health_monitor", "status": "WARN", "timestamp": timestamp_str, "duration_ms": 201, "details": {"checks": []}},
    ]

    result = asyncio.run(run(fake_results))
    print(result["details"]["plain_text_summary"])
    print("\nReport path:", result["details"]["report_path"])
